version: "3.8"
services:
  gateway:
    build: gateway
    image: gateway
    hostname: localhost
    ports:
      - "8080:8080"
    environment:
      - SERVER_URL=http://server:9090
    depends_on:
      - server
      - db
  server:
    build: server
    image: server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db
  db:
    image: postgres:14.6
    ports:
      - "6541:5432"
    volumes:
      - ./server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres