version: "3.5"
services:
  gateway:
    build: gateway
    image: gateway
    ports:
      - "8080:8080"
    environment:
      - SERVER_URL=http://server:8082
    depends_on:
      - server
      - db
    networks:
      - shareit_network
  server:
    build: server
    image: server
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db
    networks:
      - shareit_network
  db:
    image: postgres:14.6
    ports:
      - "6541:5432"
    volumes:
      - ./server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - shareit_network
networks:
  shareit_network:
    driver: bridge