CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
    );
CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(512)                            NOT NULL,
    owner_id    BIGINT,
    request_id  BIGINT,
    is_available BOOLEAN
    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT fk_item FOREIGN KEY (owner_id) references users (id)
    );
CREATE TABLE IF NOT EXISTS booking
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description        VARCHAR(255)                            NOT NULL,
    item_id             BIGINT ,
    owner_id            BIGINT,
    time_created        TIMESTAMP,
    CONSTRAINT pk_booking_id PRIMARY KEY (id)
    CONSTRAINT fk_booking_to_items FOREIGN KEY (item_id) references items (id),
    CONSTRAINT fk_booking_to_users FOREIGN KEY (owner_id) references user (id)
    );
CREATE TABLE IF NOT EXISTS booking
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description         VARCHAR(512)                    NOT NULL,
    item_id             BIGINT,
    user_id             BIGINT,
    time_created        TIMESTAMP,
    CONSTRAINT pk_booking_id PRIMARY KEY (id)
    CONSTRAINT fk_booking_to_items FOREIGN KEY (item_id) references items (id),
    CONSTRAINT fk_booking_to_users FOREIGN KEY (user_id) references user (id)
    );
