CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
    );
CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(512)                            NOT NULL,
    owner_id    BIGINT,
    request_id  BIGINT,
    is_available BOOLEAN,
    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT fk_item FOREIGN KEY (owner_id) references users (id)
    );
CREATE TABLE IF NOT EXISTS booking
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date         TIMESTAMP WITHOUT TIME ZONE,
    end_date           TIMESTAMP WITHOUT TIME ZONE,
    item_id             BIGINT,
    booker_id           BIGINT,
    status              VARCHAR(255),
    CONSTRAINT pk_booking_id PRIMARY KEY (id),
    CONSTRAINT fk_booking_to_items FOREIGN KEY (item_id) references items (id),
    CONSTRAINT fk_booking_to_users FOREIGN KEY (booker_id) references users (id)
    );
CREATE TABLE IF NOT EXISTS requests
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description         VARCHAR(255),
    requestor_id        BIGINT,
    CONSTRAINT pk_request_id PRIMARY KEY (id),
    CONSTRAINT fk_requests_to_users FOREIGN KEY (requestor_id) references users (id)
    );
CREATE TABLE IF NOT EXISTS comments
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text                VARCHAR(255),
    item_id             BIGINT,
    author_id           BIGINT,
    CONSTRAINT pk_comment_id PRIMARY KEY (id),
    CONSTRAINT fk_comments_to_items FOREIGN KEY (item_id) references items (id),
    CONSTRAINT fk_comments_to_users FOREIGN KEY (author_id) references users (id)
    );